disabled_rules:
  - comma
  - identifier_name
  - private_over_fileprivate
  - redundant_optional_initialization
  - trailing_comma
  - type_name

colon:
  flexible_right_spacing: true

line_length:
  warning: 350
  error: 500

exclude:
  - ./*/ComplicationController.swift
  - ./*/ExtensionDelegate.swift
